from enum import IntEnum

class Hashes(IntEnum):
    SKILL_W_IS_CASTING = 2345
    SKILL_W_IS_UP = 9378
    SKILL_W_IS_ATTACHED = 9953
    RED_SIDE_BLUE_CHECK = 848
    RED_SIDE_RED_CHECK = 215
    BLUE_SIDE_BLUE_CHECK = 2051
    BLUE_SIDE_RED_CHECK = 133
    EMPTY_PIXEL_BAR = 3
    EMPTY_PIXEL_BAR_ALLY = 20

class Buffers(IntEnum):
    BUFFER_ACTION_DELAY = .5
    BUFFER_MOUSE_MOVEMENT = .02
    BUFFER_SKILL_LEVELING = .03
    BUFFER_ABILITY_CASTED = .03
    BUFFER_WINDOW_FOCUSED = .02